application: nepainternships #this is the app id created at https//:www.console.developers.google.com
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /pics
  static_dir: pics
- url: /stylesheets
  static_dir: stylesheets
- url: /javascript
  static_dir: javascript
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
